### ISSUE TITLE
The README.md of this repo should include a link to the CSS

### ISSUE THREAD

**Issue by djave-co** [lucpotage/vue-katex#1]
In the readme of this project, neither the installation or usage instructions mention that you need to include the CSS file found here https://github.com/Khan/KaTeX#usage in order for the SVGs to render correctly.

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.9.0-alpha2/katex.min.css" integrity="sha384-exe4Ak6B0EoJI0ogGxjJ8rn+RN3ftPnEQrGwX59KTCl5ybGzvHGKjhPKk/KC3abb" crossorigin="anonymous">

It would be good for first time users if it mentioned it or included adding the CSS as a step. Thanks!

**Comment by watonyweng** [comment]
I write the below code in my vue component. 
`@import "../node_modules/katex/dist/katex.min.css"`
and display the right katex.
![code](https://user-images.githubusercontent.com/2574065/34860058-ce44bdfe-f795-11e7-8b54-b72f2282084e.png)

**Comment by lucpotage** [comment]
I now mention this in the README. Thank you.
