### ISSUE TITLE
Release version 0.2.2 to npm

### ISSUE THREAD

**Issue by shadskii** [lucpotage/vue-katex#15]
Master is currently at 0.2.2 but the latest version on npm is 0.2.1. One of the projects I work on is currently using 0.2.1 but is experiencing a bug with it. I fixed that bug in my last PR and bumped the version to 0.2.2. 

Thanks,

Jake

**Comment by lucpotage** [comment]
I completely forgot to publish on npm. I just did it. Sorry! 😅

**Comment by shadskii** [comment]
No worries, thanks for doing it!
