### ISSUE TITLE
v-katex auto render, not rerendering

### ISSUE THREAD

**Issue by jassehomar** [lucpotage/vue-katex#19]
Hello Community,

I am trying to use **v-katex:auto** to auto render a value from an input. I bind the value to output to my input but it's not working. Does anyone have an idea?

**Comment by lucpotage** [comment]
Hi @jassehomar, just to be sure, did you add the KaTeX stylesheet to the project as well?

**Comment by lucpotage** [comment]
I’m closing this issue after 1 month of inactivity.
