### ISSUE TITLE
v-katex  里面如果有标签怎么办？

### ISSUE THREAD

**Issue by appbeijing** [lucpotage/vue-katex#22]
v-katex  我试了一下，文本是可以的，但是如果里面有标签是不支持的，这个怎么解决？

**Comment by lucpotage** [comment]
Hello @appbeijing, I translated your message with Google so I hope I understood your request.
If you are speaking about `\label`, it seems not supported by KaTeX so far.

https://github.com/KaTeX/KaTeX/issues/2003

If it's something else, please provide more details.
