### ISSUE TITLE
how to force re-rendering when content changes?

### ISSUE THREAD

**Issue by nkmnz** [lucpotage/vue-katex#23]
Hi! Great project, enjoy using it so far :) 
I have a span-element with the `v-katex:auto` attribute, to which I pass user input. How can I call the `renderMathInElement` function from my component?

**Comment by nkmnz** [comment]
Nevermind, found a solution – I pass the content as a key to the span :)

**Comment by kenkoedu** [comment]
> Nevermind, found a solution – I pass the content as a key to the span :)

Just wanna put an example for those who are going to view the topic later:

```vue
<template>
  <div>
    <input v-model="question" />
    <div v-katex:auto :key="question">{{question}}</div>
  </div>
</template>
```

Is that what you did, I guess?
