### ISSUE TITLE
how to use this by CDN way

### ISSUE THREAD

**Issue by badongdyc** [lucpotage/vue-katex#24]

**Comment by lucpotage** [comment]
https://cdn.jsdelivr.net/npm/vue-katex@0.4.0/dist/vue-katex.min.js

The full list is available here too: https://cdn.jsdelivr.net/npm/vue-katex@0.4.0/dist/

**Comment by badongdyc** [comment]
@lucpotage Thank you very much

**Comment by TCMAD** [comment]
Can anyone tell me or give me an example on how to use the CDN please ?
When I try to load it on my `index.html` and test on my components, I've just have errors on my console.

**Comment by lucpotage** [comment]
Hello @TCMAD, do you have a reproduction link so that I can help you? Make sure you load the script after Vue lib.

**Comment by TCMAD** [comment]
Hi @lucpotage , I tried to generate a simple codesandbox but I failed (my CDNs aren't compatibles). 
But you can find below a simple code of my test (No dependencies/packages) : 
``` HTML
<html>
<!-- index.html -->
<head>
    <title>Parcel Sandbox</title>
    <meta charset="UTF-8" />
</head>

<body>
    <div id="app">
        <test></test>
    </div>

    <!-- Vue.js -->
    <script src="https://cdn.jsdelivr.net/npm/vue/dist/vue.js"></script>

    <!-- Http-vue-loader-->
    <!-- https://github.com/FranckFreiburger/http-vue-loader -->
    <script src="https://unpkg.com/http-vue-loader"></script>

    <!-- Vue-Katex -->
    <script src="https://cdn.jsdelivr.net/npm/vue-katex@0.5.0/dist/vue-katex.min.js"></script>

    <script src="./index.js"></script>


</body>

</html>
```

```javascript
/*index.js*/
var App = new Vue({
    el: "#app",
    components: {
      'test' : httpVueLoader("./test.vue")
    }
  });
```

```vue.js
/*test.vue*/
<template>
  <div>
    Test
    <div v-katex="'\\frac{a_i}{1+x}'"></div>
  </div>
</template>
```

**Comment by lucpotage** [comment]
Thank you for the code. I actually have no idea why it does not work. Maybe @shadskii knows? I personally use webpack.
