### ISSUE TITLE
fontSize

### ISSUE THREAD

**Issue by liranandroid** [lucpotage/vue-katex#25]
![1590310850(1)](https://user-images.githubusercontent.com/53393414/82750062-4ee3ab80-9de0-11ea-86c9-2e186974c86b.jpg)

It shrinked the fontsize,which is what I don't want .How to fix it?How can I connect with U?

**Comment by lucpotage** [comment]
Hello @liranandroid, your issue is not related to this plugin but to KaTeX.

Please read the KaTeX documentation for more info about fractions: https://katex.org/docs/supported.html#fractions-and-binomials
