### ISSUE TITLE
Katex not render on Chrome Browser

### ISSUE THREAD

**Issue by sontt-1215** [lucpotage/vue-katex#34]
![Screenshot from 2020-12-17 09-05-56](https://user-images.githubusercontent.com/49391617/102434333-24409500-4047-11eb-8d10-c5710f594607.png)
 I can't see katex in chrome browser (firefox is ok)
 This is in firefox browser
![Screenshot from 2020-12-17 09-07-59](https://user-images.githubusercontent.com/49391617/102434469-69fd5d80-4047-11eb-9e6f-dc4d74006f01.png)
 Please help me !!!!
@lucpotage 
@shadskii

**Comment by shadskii** [comment]
@sontt-1215 Can you provide the relevant snippets for the problem? Without seeing how you've implemented this, I'm not sure how to help.

**Comment by sontt-1215** [comment]
sorry, i think that i was a bit confused
