### ISSUE TITLE
Need for more examples

### ISSUE THREAD

**Issue by MountainAndMorning** [lucpotage/vue-katex#36]
It seems that some important feature of katex does not be included in vue-katex such as \tag and \begin{matrix}. If it is not true, maybe more examples can be included to help using it. Thanks.

**Comment by lucpotage** [comment]
Hello @MountainAndMorning,

Without any reproduction link, it was difficult to guess your problem.
Here is a working example with matrices: https://codesandbox.io/s/matrices-with-vue-katex-8b9v5

As you can see, you need to escape all backslash chars in your string expression.

**Comment by 4n70w4** [comment]
https://tiddlywiki.com/plugins/tiddlywiki/katex/
