### ISSUE TITLE
Overline is going uppercase

### ISSUE THREAD

**Issue by ThiNepo** [lucpotage/vue-katex#47]
Hello, 

When I try to use overline on katex-element it goes uppercase. Do you guys have any idea why it is happening?

Thanks!

#### Example

```html
<katex-element expression="\overline{a b}" :throw-on-error="false"></katex-element>
```

result in 

![Overline ab](https://user-images.githubusercontent.com/11523871/120932207-2aa9f280-c6f5-11eb-81be-f5ab29a994f9.png)

**Comment by lucpotage** [comment]
Hi, knowing that vue-katex is just a wrapper, I have no idea why this is happening. Do you have a reproduction link?

**Comment by ThiNepo** [comment]
Never mind, sorry for bothering you. 

It was a collision with the CSS from Vuetify.

```css
.v-application .overline {
     text-transform: uppercase;
}
```

🤦‍♂️
