### ISSUE TITLE
options are ignored when using v-katex:auto={ options }

### ISSUE THREAD

**Issue by bendeutz** [lucpotage/vue-katex#51]
Heys guys,

maybe someone can help me out here. I want to use $-signs as delimiters and i tried this code-snippet:

`v-katex:auto="{delimiters: [{ left: '$', right: '$', display: false }],}"`

For some reason the delimiters are are still standard. Any ideas?

**Comment by shadskii** [comment]
Hi,

It looks like your problem is the `delimiters` config should be nested under `options`. The follow snippet will give you your desired result.

```js
v-katex:auto="{ options: { delimiters: [{ left: '$', right: '$', display: false }] } }"
```

Hope this helps!
