### ISSUE TITLE
Core-js not found error

### ISSUE THREAD

**Issue by askcreative** [lucpotage/vue-katex#6]
ERROR in ./node_modules/vue-katex/dist/vue-katex.es.min.js
Module not found: Error: Can't resolve 'core-js/modules/es6.object.assign'

ERROR in ./node_modules/vue-katex/dist/vue-katex.es.min.js
Module not found: Error: Can't resolve 'core-js/modules/es6.number.constructor'

ERROR in ./node_modules/vue-katex/dist/vue-katex.es.min.js
Module not found: Error: Can't resolve 'core-js/modules/es6.function.name'

I just tried to install this in a new vue project to test it out and am getting the above error.

**Comment by watonyweng** [comment]
@askcreative Your project may be built on [vue-cli](https://github.com/vuejs/vue-cli), it dependency on [core-js](https://github.com/zloirock/core-js)
