### ISSUE TITLE
Release new version to npm

### ISSUE THREAD

**Issue by shadskii** [lucpotage/vue-katex#9]
The latest version of this package has not been release to npm. The current version on npm is trailing by two minor versions (0.2.0 on npm vs 0.2.2 on github). 

@lucpotage I believe that this project is important and I would like to continue to contribute to it. I can provide a lot more help to you if I am able to take a more hands on role in this project. I would like to discuss with you what this would entail. Please email me at jake.k.hassel@gmail.com. 

I look forward to working with you. :smile:

Jake

**Comment by lucpotage** [comment]
Hello @shadskii. Thanks for your input.

I added you as a collaborator on this repo. 🤝 I will make sure to be more reactive for the publications.
I recently wanted to updated all the packages to fix the vulnerability warning but it was not a success…
I also upgraded KaTeX to the latest version (0.11.0) but the snapshots didn't work anymore. If you have time to fix this, I would be really glad.

Thanks again for your help.
